---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: isjanjaaperal.local.dev
    timezone: Europe/Amsterdam
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
#    - mysql
    - phpcommon
    - app
